#!/usr/bin/env bash
LC_ALL=C
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
source /usr/bin/variables
live_check
optimizacion_1
apt -q update
$insta xanadu-repo
apt -q update
apt -y full-upgrade
source /usr/bin/miarranque-mem
limpiar_1
rm -f /run/$(basename $0).pid
exit 0
