#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
IFS=" "
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
exec 2>/var/log/$(basename $0).log
source /usr/bin/variables
rootcli
live_check
optimizacion_1
apt -q update
$insta xanadu-repo
apt -q update
apt -y full-upgrade
$insta xanadu-clean
apt -y purge xanadu-clean
apt -y autoremove
apt -y purge $(deborphan --libdevel) $(deborphan --find-config) $(deborphan)
source /usr/bin/miarranque-mem
limpiar_1
rm -f /run/$(basename $0).pid
exit 0
