#!/usr/bin/env bash
LC_ALL=C
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
source /usr/bin/variables
zenity --text-info --title="Adicionales" --filename=/usr/bin/mensaje-adicionales.txt
if [[ $? == 0 ]] ; then
	echo 1 > /dev/null
else
	exit 0
fi

mio=$(yad --sticky --fixed --center --width=360 --height=420 --text="Xanadu GNU/Linux $(cat /etc/os-release | grep 'VERSION=' | cut -c 10-14)" --no-click --list --title="Adicionales" --column=Acciones "Gestionar Firewall" "Como activar la persistencia" "Activar persistencia automaticamente" "Reparar Hora" "Fillzero" "Iniciar Compton" "Detener Compton" "Ddclone")

if [ "$mio" = "Como activar la persistencia|" ]; then
	zenity --text-info --title="Persistencia" --filename=$persistencia
	if [[ $? == 0 ]] ; then
		echo 1 > /dev/null
	else
		exit 0
	fi

elif [ "$mio" = "Activar persistencia automaticamente|" ]; then
	source /usr/bin/mipersistencia

elif [ "$mio" = "Reparar Hora|" ]; then
	$advertencia --text="Esta opción tratara de reparar la forma en la que se muestra la hora en su ordenador."
	hwclock --systohc
	systemctl restart ntp

elif [ "$mio" = "Iniciar Compton|" ]; then
	$advertencia --text="Esta opción activara el gestor de composición compton aumentando dramáticamente el consumo de recursos en su equipo."
	/usr/bin/compton --config /etc/compton.conf -b
	
elif [ "$mio" = "Detener Compton|" ]; then
	killall compton
	$final --text="Compton se ha detenido."

elif [ "$mio" = "Gestionar Firewall|" ]; then
	gufw

elif [ "$mio" = "Fillzero|" ]; then
	source /usr/bin/fillzero

elif [ "$mio" = "Ddclone|" ]; then
	source /usr/bin/ddclone

else
	echo 1 > /dev/null

fi
rm -f /run/$(basename $0).pid
exit 0
