#!/usr/bin/env bash
LC_ALL=C
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
source /usr/bin/variables
case "$1" in
	tor_on)
		if [[ -f "$lock" ]]; then
			echo "Tor ya se esta ejecutando."
		else
    			/usr/bin/tor-on
			echo "Espere mientras se inicia TOR se le notificara al completarse la tarea."
			sleep 30
			echo "Inicio completado. Si utiliza un navegador diferente de Iceweasel, introduzca la siguiente configuración de PROXY en su navegador: localhost (o el ip del equipo) puerto 8118 (9151 para socks) y localhost (o el ip del equipo) puerto 9050 para las otras aplicaciones que usen socks."
		fi
		;;

	tor_monitor)
		sudo -u debian-tor arm
		;;

	tor_off)
	    	if [[ -f "$lock" ]]; then
			/usr/bin/tor-off
			echo "Servicio finalizado exitosamente."
		else
			echo "Tor no se esta ejecutando."
		fi
		;;

	router_on)
		if [[ -f "$lock3" ]]; then
			echo "El Router WiFi Tor ya se esta ejecutando."
		else
	    		echo "Espere mientras se inicia TOR se le notificara al completarse la tarea."
			/usr/bin/mirouter-on
			echo "Inicio completado, se recomienda no usar la pc durante la ejecucion del router wifi."
			echo "SSID: "$(grep -n "ssid=" hostapd.conf | grep "7" | cut -c 8-18)
			echo "Password: "$(grep "wpa_passphrase" /etc/hostapd/hostapd.conf | cut -c 16-26)
		fi
		;;

	router_off)
	    	if [[ -f "$lock3" ]]; then
			mirouter_0/usr/bin/mirouter-off
			echo "Servicio finalizado exitosamente."
		else
			echo "El Router WiFi Tor no se esta ejecutando."
		fi
		;;

	i2p_on)
	    	if [[ -f "$lock" ]]; then
			echo "I2p no puede ejecutarse conjuntamente con tor."
		else
			if [[ -f "$lock2" ]]; then
				echo "I2p ya se esta ejecutando."
			else
    				/usr/bin/i2p-on
			fi
		fi
		;;

	i2p_off)
		if [[ -f "$lock2" ]]; then
			/usr/bin/i2p-off
			echo "Servicio finalizado exitosamente."
		else
			echo "I2p no se esta ejecutando."
		fi
		;;

	hora)
		hora_1
		echo "Esta opción tratara de reparar la forma en la que se muestra la hora en su ordenador."
		;;

	*)
            	echo "USO: $(basename $0) {tor_on|tor_monitor|tor_off|router_on|router_off|i2p_on|i2p_off|hora}"
		;;

esac
rm -f /run/$(basename $0).pid
exit 0
