#!/usr/bin/env bash
LC_ALL=C
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
source /usr/bin/variables
live_check
case "$1" in
	minimal)
		optimizacion_1
		$insta xanadu-headless
		apt -y autoremove
		apt -y purge $(deborphan --libdevel) $(deborphan --find-config) $(deborphan)
		limpiar_1
		;;

	office)
		optimizacion_1
		apt -y purge autopsy chkrootkit wifite wireshark zenmap ethtool fsarchiver yersinia 0trace amap arp-scan gtkorphan tmux gtkhash x11vnc ssvnc filezilla pidgin pidgin-otr transmission axel macchanger-gtk fail2ban iptraf-ng arptables gufw ntp tcptraceroute mtr-tiny wget clonezilla extundelete foremost magicrescue testdisk scalpel hostapd polipo privoxy socat tor tor-arm tsocks torsocks obfs4proxy apt-transport-tor connect-proxy proxychains secure-delete aide-common ophcrack cmospwd psad mat bleachbit lzip lzma lzop
		$insta playonlinux xanadu-archive-keyring xanadu-repo
		rm -f /usr/share/applications/Adicionales.desktop
		rm -f /etc/apt/sources.list.d/kali.list
		rm -f /etc/apt/sources.list.d/liquorix.list
		rm -f /etc/apt/sources.list.d/tor.list
		limpiar_1
		;;

	*)
		echo "Este script adapta una instalacion de Xanadu GNU/Linux para hacerla"
		echo "apta para su uso en oficinas o en entornos headless..."
		echo "USO: $(basename $0) {minimal|office}"
		;;
esac
rm -f /run/$(basename $0).pid
exit 0
