#!/usr/bin/env bash
LC_ALL=C
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
source /usr/bin/variables
live_check
case "$1" in
	minimal)
		optimizacion_1
		$insta xanadu-headless
		apt -y autoremove
		apt -y purge $(deborphan --libdevel) $(deborphan --find-config) $(deborphan)
		limpiar_1
		;;

	office)
		optimizacion_1
		$insta xanadu-sfw
		limpiar_1
		;;

	*)
		echo "Este script adapta una instalacion de Xanadu GNU/Linux para hacerla"
		echo "apta para su uso en oficinas o en entornos headless..."
		echo "USO: $(basename $0) {minimal|office}"
		;;
esac
rm -f /run/$(basename $0).pid
exit 0
