#!/usr/bin/env bash
LC_ALL=C
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
source /usr/bin/variables
live_check
function progress_2 () {
	$progreso --progress-text="Instalando Software, esto proceso puede tomar varios minutos, por favor espere" --title="Instalando"
}

function progress_limpiar_2 () {
	$progreso --progress-text="Realizando limpieza" --title="LIMPIEZA"
}

optimizacion_1 | $progreso --progress-text="Optimizando el sistema, por favor espere..." --title="Optimizacion"

if (( $memoria < 512000 )); then
	$advertencia --text="Se ha detectado poca RAM en su ordenador, se recomienda instalar el paquete xanadu-low para obtener ciertos programas mas adecuados a su equipo."
fi

zenity --text-info --title="Post-instalacion" --filename=/usr/bin/mensaje-post.txt

if [[ $? == 0 ]]; then
	echo 1 > /dev/null
else
	exit 0
fi

function headers_1 () {
	if [[ $(arch) = x86_64 ]] || [[ $(arch) = amd64 ]]; then
		$update
		$insta linux-headers-siduction-amd64
	else
		$update
		$insta linux-headers-siduction-686
	fi
}

function apparmor_1 () {
	$update
	$insta lightdm-gtk-greeter-settings grub-customizer icedove camorama
	if (( $memoria > 4096000 )); then
		$insta preload
	fi
}

cantidadram='--window-icon=/usr/share/icons/post-install.png --text="Debe tener un equipo con 2 Gb de RAM o mas para instalar este software."'
seguro='--window-icon=/usr/share/icons/post-install.png --text="¿Esta seguro de querer instalar este software?"'
file=$(yad --sticky --fixed --center --width=360 --height=450 --window-icon=/usr/share/icons/post-install.png --text="Xanadu GNU/Linux $(cat /etc/os-release | grep 'VERSION=' | cut -c 10-14)" --no-click --list --title="Post-instalación" --column=Acciones "Instalar Recomendados" "Instalar KDE" "Instalar GNOME" "Instalar XFCE" "Instalar Enlightenment" "Instalar Xanadu-Accessibility" "Instalar WINE" "Instalar driver ATI" "Instalar driver NVIDIA" "Instalar Xanadu-low" "Instalar HEADERS" "Instalar HPLIP-GUI" "Instalar Laptop-Mode-Tools" "Actualizar")

if [ "$file" = "Instalar KDE|" ]; then
	if (( $memoria > 2048000 )); then	
		$update
		$insta xanadu-kde | progress_2
		limpiar_1 | progress_limpiar_2
	else
		$errores $cantidadram
	fi

elif [ "$file" = "Instalar GNOME|" ]; then
	if (( $memoria > 2048000 )); then
		$update
		$insta xanadu-gnome | progress_2
		limpiar_1 | progress_limpiar_2
	else
		$errores $cantidadram
	fi	

elif [ "$file" = "Instalar XFCE|" ]; then
	$update
	$insta xanadu-xfce | progress_2
	limpiar_1 | progress_limpiar_2

elif [ "$file" = "Instalar Enlightenment|" ]; then
	$update
	$insta xanadu-enlightenment | progress_2
	limpiar_1 | progress_limpiar_2

elif [ "$file" = "Instalar Xanadu-Accessibility|" ]; then
	if (( $memoria > 2048000 )); then
		$update
		$insta xanadu-accessibility | progress_2
		limpiar_1 | progress_limpiar_2
	else
		$errores $cantidadram
	fi

elif [ "$file" = "Instalar WINE|" ]; then
	if (( $memoria > 2048000 )); then
		$update
		$insta playonlinux | progress_2
		limpiar_1 | progress_limpiar_2
	else
		$errores $cantidadram
	fi	

elif [ "$file" = "Instalar driver ATI|" ]; then
	$update
	$insta fglrx-atieventsd fglrx-control fglrx-driver fglrx-modules-dkms radeontool | progress_2
	limpiar_1 | progress_limpiar_2

elif [ "$file" = "Instalar driver NVIDIA|" ]; then
	$update
	$insta nvclock nvidia-alternative nvidia-glx nvidia-installer-cleanup nvidia-kernel-common nvidia-kernel-dkms nvidia-settings nvidia-support nvidia-vdpau-driver nvidia-detect nvidia-xconfig | progress_2
	limpiar_1 | progress_limpiar_2

elif [ "$file" = "Instalar Xanadu-low|" ]; then
	$update
	$insta xanadu-low | progress_2
	limpiar_1 | progress_limpiar_2

elif [ "$file" = "Instalar HEADERS|" ]; then
	headers_1 | progress_2
	limpiar_1 | progress_limpiar_2

elif [ "$file" = "Instalar Recomendados|" ]; then
	apparmor_1 | progress_2
	if [[ $(lscpu | grep ID | awk '{print $4}') = GenuineIntel ]];then
		$insta thermald
	fi
	limpiar_1 | progress_limpiar_2

elif [ "$file" = "Instalar HPLIP-GUI|" ]; then
	$update
	$insta hplip-gui | progress_2
	limpiar_1 | progress_limpiar_2

elif [ "$file" = "Instalar Laptop-Mode-Tools|" ]; then
	if $advertencia --text="Este software solo debe ser instalado en una laptop ¿desea continuar?"; then
		$update
		$insta laptop-mode-tools | progress_2
		systemctl enable laptop-mode
		limpiar_1 | progress_limpiar_2
	else
		source $0
	fi	

elif [ "$file" = "Actualizar|" ]; then
	xterm -e /usr/bin/actualizar

else
echo 1 > /dev/null

fi
rm -f /run/$(basename $0).pid
exit 0
