#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C

trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
source /usr/bin/variables

function aide_on () {
	aideinit -y -f
	mv -f -v /var/lib/aide/aide.db.new /var/lib/aide/aide.db
}

function psad_on () {
	systemctl enable psad
	sed -i 's_HOSTNAME                    xanadu;_'HOSTNAME                    $(hostname);'_g' /etc/psad/psad.conf
	systemctl start psad
	psad --sig-update
	psad -H
}

function fail_on () {
	systemctl enable fail2ban
	systemctl start fail2ban
}

function ntp_on () {
	systemctl enable ntp
	systemctl start ntp
}

opts=$(yad --window-icon=/usr/share/icons/lock-close.png --center --list --title="Activar elementos de seguridad" --text="Marque las opciones que usted quiere activar. Los servicios se activaran con sus configuraciones por defecto es necesario que el usuario las modifique de acuerdo a sus necesidades." --checklist --column "Marque" --column "Num" --column "Opcion" --width=590 --height=525 --button="Aceptar":0 --button="Salir":1\
  FALSE 01 "Activar AIDE" \
  FALSE 02 "Activar Fail2ban" \
  FALSE 03 "Activar PSAD" \
  FALSE 04 "Activar NTP" \
  TRUE 05 "Activar todos")

if [[ $? = 1 ]]; then
	exit 0
fi

if $(echo $opts | grep -q 01); then 
	aide_on
fi

if $(echo $opts | grep -q 02); then
	fail_on
fi

if $(echo $opts | grep -q 03); then
	psad_on
fi

if $(echo $opts | grep -q 04); then
	ntp_on
fi

if $(echo $opts | grep -q 05); then
	aide_on
	psad_on
	fail_on
	ntp_on
fi

$advertencia --window-icon=/usr/share/icons/lock-close.png --timeout=7 --text="Finalizado"

rm -f /run/$(basename $0).pid
exit 0
