#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
miver="1"
memoria=$(grep "MemTotal" /proc/meminfo | awk '{print $2}')
cpu=$(lscpu | grep "MHz" | awk '{print $3}')
miswap=$(fdisk -l | grep "swap" | awk '{print $1}')
quien=$(who | cut -d' ' -f1 | sort | uniq)
update="apt -q update"
insta="apt -q -y install"
miyad='yad --skip-taskbar --button=ACEPTAR:0 --fixed --center --text-align=fill --borders=6'
errores='yad --skip-taskbar --button=ACEPTAR:0 --fixed --center --window-icon=error --text-align=fill --borders=6 --timeout=3 --title="Error"'
advertencia='yad --skip-taskbar --button=ACEPTAR:0 --fixed --center --text-align=fill --borders=6 --title="Advertencia"'
final='yad --skip-taskbar --button=ACEPTAR:0 --fixed --center --text-align=fill --borders=6 --timeout=3 --title="Finalizado"'
progreso='yad --fixed --progress --pulsate --auto-close --skip-taskbar --center'
null="echo 1 > /dev/null"

function yadinstall () {
	if ! [[ -f /usr/bin/yad ]]; then
		echo "ERROR: Yad NO se encuentra instalado" > /var/log/xanadu-error.log
		exit 1
	fi
}

function rootyad () {
	yadinstall
	if [[ "$EUID" != "0" ]]; then
		yad --skip-taskbar --button=ACEPTAR:0 --fixed --center --text-align=fill --borders=6 --timeout=3 --title="ERROR" --text="ERROR: Debes ser root."
		exit 1
	fi
}

function rootcli () {
	if [[ "$EUID" != "0" ]]; then
		echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
		exit 1
	fi
}

function live_check () {
	if [[ -d /lib/live/mount/rootfs ]]; then
		$errores --text="Este programa no se puede ejecutar en modo live."
		exit 1
	fi
}

function nolive_check () {
	if ! [[ -d /lib/live/mount/rootfs ]]; then
		$errores --text="Este programa debe ejecutarse en modo live."
		exit 1
	fi
}

function limpiar_1 () {
	history -c
	apt-get clean
	rm -rf /tmp/*
	rm -rf /var/tmp/*
	rm -rf /var/cache/apt/*
	rm -rf /var/cache/apt/archives/*
	rm -rf /root/.local/share/Trash/*
	rm -rf /home/*/.cache/*
	rm -rf /home/*/.local/share/Trash/*
	rm -rf /home/*/.mozilla/firefox/*/*Cache*
	bleachbit -o -c adobe_reader.cache chromium.cache chromium.current_session chromium.history elinks.history emesene.cache epiphany.cache firefox.url_history flash.cache flash.cookies google_chrome.cache google_chrome.history links2.history opera.cache opera.search_history opera.url_history bash.history system.cache system.clipboard system.custom system.recent_documents system.rotated_logs system.tmp system.trash &> /dev/null
}

function iptables_clean () {
	iptables -F
	iptables -X
	iptables -Z
	iptables -t nat -F
	iptables -t nat -X
	iptables -t mangle -F
	iptables -t mangle -X
	iptables -P INPUT ACCEPT
	iptables -P FORWARD ACCEPT
	iptables -P OUTPUT ACCEPT
}

function optimizacion_1 () {
	if ! [[ -f /root/.optimizado ]]; then
		if (( $memoria > 4096000 )); then
			for i in $quien; do
				echo "tmpfs /home/$i/.cache tmpfs noatime,noexec,nosuid,async,nodev,rw 0 0" >> /etc/fstab
			done
		fi
		chage -M 183 "$quien"
		adduser "$quien" sambashare
		touch /root/.optimizado
	fi
}
